title: My Blog
description: A personal space for poems, musings, and projects.
baseurl: "" # Leave blank if using a custom domain
url: "https://www.raaj.blog" # Replace with your actual domain
markdown: kramdown
plugins:
  - jekyll-sass-converter

sass:
  style: compressed